sudo: false

language: groovy

jdk:
    - openjdk7

env:
    global
    - TZ="Australia/Hobart" JAVA_OPTS="-Xmx1G -Xms512m -XX:PermSize=64m -XX:MaxPermSize=512m"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - rm -rf ~/.gvm
  - curl -s get.gvmtool.net > ~/install_gvm.sh
  - chmod 775 ~/install_gvm.sh
  - ~/install_gvm.sh
  - echo "gvm_auto_answer=true" > ~/.gvm/etc/config
  - source ~/.gvm/bin/gvm-init.sh
  - gvm install grails 2.4.4 || true

  
script:
  - "grails clean && grails upgrade --non-interactive && grails test-app functional: --non-interactive --stacktrace"
